DROP TABLE MCKINSEY_USER.CALL_HISTORY_ARPT_TMP CASCADE CONSTRAINTS;
 
CREATE TABLE MCKINSEY_USER.CALL_HISTORY_ARPT_TMP
(
  SERVED_MSISDN  VARCHAR2(50 BYTE),
  CALLED_NUMBER  VARCHAR2(50 BYTE),
  CALL_TYPE      VARCHAR2(50 BYTE),
  DURATION       VARCHAR2(50 BYTE),
  SERVED_IMSI    VARCHAR2(50 BYTE),
  SERVED_IMEI    VARCHAR2(50 BYTE),
  CELL_ID        VARCHAR2(50 BYTE),
  UTC_TIMESTAMP  VARCHAR2(50 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY CRS_DIR_FILES2
     ACCESS PARAMETERS
       ( records delimited BY '\n'
     badfile USAGE_DIR_BAD:'ers%a_%p.bad'
     LOGFILE USAGE_DIR_LOG:'ers%a_%p.log'
     fields terminated BY ','   
     MISSING FIELD VALUES ARE NULL
  
          )
     LOCATION (CRS_DIR_FILES2:'ARPT_CALL_HISTORYIMEI420170705 .csv')
  )
REJECT LIMIT 0
NOPARALLEL
NOMONITORING;
 
-----arpt call history
select SERVED_MSISDN APPELANTS,
       CALLED_NUMBER APPELES,
       SUBSTR(UTC_TIMESTAMP,1,LENGTH(UTC_TIMESTAMP)-1) DATES,
       substr(UTC_TIMESTAMP,12,2) HEURES,
       DURATION DUREE,
       SERVED_IMSI IMSI,
       SERVED_IMEI IMEI,
       GOUVERNORATS LOCALISATION,
       CELL_ID CELLULE_ID,
       CELLNAMES CELLULE_NAME,
       VILLE,
       COMMUNES PREFECTURE,
       REGION_NATURELLE REGION,
       CALL_TYPE TYPE
from CALL_HISTORY_ARPT_TMP a, IT_MK_CELLID_FINAL_2013 b where b.CELLID=a.CELL_ID
and to_date(substr(UTC_TIMESTAMP,1,10),'dd/mm/yyyy') between   to_date('01/10/2015','dd/mm/yyyy') and to_date('31/10/2015','dd/mm/yyyy')

