SELECT a.MSISDN MSISDN_ECW,a.OTHERID OTHERID_ECW,a.OTHERID_TYPE OTHERID_TYPE_ECW,a.ACCOUNT_NAME ACCOUNT_NAME_ECW, b.MSISDN MSISDN_CLM, b.ID_TYPE CLM_ID_TYPE, b.ID_DESCRIPTION CLM_ID_DESCRIPTION, b.ID_NO CLM_ID_NUMBER, b.NAME CLM_NAME
FROM (
SELECT MSISDN,OTHERID,OTHERID_TYPE,ACCOUNT_NAME FROM  REPORT_USER.IT_MOMO_ACCOUNT_CREATE_ON_ECW
UNION ALL
SELECT MSISDN,OTHERID,OTHERID_TYPE,ACCOUNT_NAME FROM REPORT_USER.IT_MOMO_ACNT_CREATE_ON_FUNDAMO) a,
(SELECT '224'||SUBNO MSISDN, ID_TYPE, ID_DESCRIPTION, ID_NO,NAME  FROM REPORT_USER.REG_TABS_DEPARTEMENT_DAILY) b
WHERE A.MSISDN=B.MSISDN 



and A.MSISDN not in (select MSISDN_ECW from ECW_CLM_TEMP)