select t1.TRANSACTION_ID_IN as TRANSACTION_ID,
       t2.DELIVERY_DATE,
       t1.DATE_RECEIVE,
       t1.PRODUCT_CODE,
       t1.PRODUCT_NAME,
       t2.STORE_OUT_CODE,
       t2.STORE_OUT_NAME,
       t2.QUANTITY_OUT,
       t1.STORE_RECEIVE_CODE,
       t1.STORE_RECEIVE_NAME,
          t1.STATUS_TRANSACTION,
       t1.QUANTITY_RECEIVE,
       t1.FROM_SERIAL_RECEIVE,
       t1.END_SERIAL_RECEIVE
from (
             select TDETAILOPERATION.noPieceOrigine AS TRANSACTION_ID_IN,
             TPRODUITCOMMERCIAL.code AS PRODUCT_CODE,
             TPRODUITCOMMERCIAL.Caption AS PRODUCT_NAME,
             TSITECOMMERCIALE.Caption AS STORE_RECEIVE_NAME,
             TSITECOMMERCIALE.code AS STORE_RECEIVE_CODE,/*
             TCAPACITEENTREESTOCK.NUM_DEBUT AS FROM_SERIAL_RECEIVE,
             TCAPACITEENTREESTOCK.NUM_FIN AS END_SERIAL_RECEIVE,*/
             TCAPACITEENTREESTOCK.deb AS FROM_SERIAL_RECEIVE,
             TCAPACITEENTREESTOCK.fin AS END_SERIAL_RECEIVE,
             TCAPACITEENTREESTOCK.quantiteEntree AS QUANTITY_RECEIVE,
             TDETAILOPERATION.libelleEtape,
             TDETAILOPERATION.typeOperation AS TRANSACTION_TYPE_IN,
             TCAPACITEENTREESTOCK.UpdDate as DATE_RECEIVE,
             TDETAILOPERATION.libelleEtape as STATUS_TRANSACTION
             from TDETAILOPERATION,TSITECOMMERCIALE,TCAPACITEENTREESTOCK,TPRODUITCOMMERCIAL 
             where TSITECOMMERCIALE.oid=TDETAILOPERATION.oidDepot
             and TDETAILOPERATION.oid=TCAPACITEENTREESTOCK.oidOrigineOperation
             and TPRODUITCOMMERCIAL.oidProduitLivre=TDETAILOPERATION.oidProduitLivre
             and TDETAILOPERATION.typeOperation='7'
             AND TPRODUITCOMMERCIAL.code LIKE'C1121-02-06%'
             ) t1,
             (
             select TDETAILOPERATION.noPieceOrigine AS TRANSACTION_ID_OUT,
             TPRODUITCOMMERCIAL.code AS PRODUCT_CODE,
             TPRODUITCOMMERCIAL.Caption AS PRODUCT_NAME,
             TSITECOMMERCIALE.Caption AS STORE_OUT_NAME,
             TSITECOMMERCIALE.code AS STORE_OUT_CODE,
             TCAPACITESORTIESTOCK.quantiteSortie AS QUANTITY_OUT,
             TDETAILOPERATION.libelleEtape,
             TDETAILOPERATION.typeOperation  AS TRANSACTION_TYPE_OUT,
             TCAPACITESORTIESTOCK.UpdDate as DELIVERY_DATE 
             from TDETAILOPERATION,TSITECOMMERCIALE,TCAPACITESORTIESTOCK,TPRODUITCOMMERCIAL 
             where TSITECOMMERCIALE.oid=TDETAILOPERATION.oidDepot
             and TDETAILOPERATION.oid=TCAPACITESORTIESTOCK.oidOrigineOperation
             and TPRODUITCOMMERCIAL.oidProduitLivre=TDETAILOPERATION.oidProduitLivre
             and TDETAILOPERATION.typeOperation='6'
             AND TPRODUITCOMMERCIAL.code LIKE'C1121-02-06%'  
             ) t2
where t1.TRANSACTION_ID_IN=t2.TRANSACTION_ID_OUT
AND t1.TRANSACTION_TYPE_IN=t2.TRANSACTION_TYPE_OUT+1
and DELIVERY_DATE>='2018-01-01'
-- and t1.TRANSACTION_ID_IN in('TR03000085','TR03000076')

--C1111 VOUCHERS code
