create table First_call_rev as
(select SERVED_MSISDN, sum(TOTAL_COST) TOTAL_COST
from report_user.IT_MIS_USAGE_EVENTS_DTL_12
where  SERVED_MSISDN IN (select '224'||MSISDN from MSISDN_TEMP)
group by SERVED_MSISDN)

SELECT A.MSISDN, B.STATUS_MSISDN, B.FIRST_CALL_DATE, C.total_cost REVENUE
FROM MSISDN_TEMP A, REPORT_USER.IT_DR_IN_STATUS_SUBSCRIBERS B, First_call_rev C
where A.MSISDN=B.ACCOUNT_MSISDN(+) and '224'||A.MSISDN=C.SERVED_MSISDN(+)