alter table MCKINSEY_USER.CALL_HISTORY_ARPT_TMP LOCATION (CRS_DIR_FILES2:'ARPT_CALL_HISTORY_NUMBER_Req_0463_20190509.csv'); 
commit;

-----arpt call history
select SERVED_MSISDN APPELANTS,
       CALLED_NUMBER APPELES,
       SUBSTR(UTC_TIMESTAMP,1,LENGTH(UTC_TIMESTAMP)-1) DATES,
       substr(UTC_TIMESTAMP,12,2) HEURES,
       DURATION DUREE,
       SERVED_IMSI IMSI,
       SERVED_IMEI IMEI,
       GOUVERNORATS LOCALISATION,
       CELL_ID CELLULE_ID,
       CELLNAMES CELLULE_NAME,
       VILLE,
       COMMUNES PREFECTURE,
       REGION_NATURELLE REGION,
       CALL_TYPE TYPE
from MCKINSEY_USER.CALL_HISTORY_ARPT_TMP a, MCKINSEY_USER.IT_MK_CELLID_FINAL_2013 b where b.CELLID=a.CELL_ID
and to_date(substr(UTC_TIMESTAMP,1,10),'dd/mm/yyyy') between   to_date('01/04/2019','dd/mm/yyyy') and to_date('09/05/2019','dd/mm/yyyy')
and length(UTC_TIMESTAMP)>=10

---------METHODE FOR OLD TRANSACTIONS-------------
select max(MAX_TRANSACTION) MAX_TRANSACTION
from IT_MIS_RGS90_MOC_MTC_TEMP          
where CALLED_NUMBER='224662133569'

SELECT *
FROM IT_MIS_RGS_MOC_LOAD_MAR18 PARTITION(D20180307_MOC_EVENTS)
where (CALLING_NUMBER='224662133569' or CALLED_NUMBER='224662133569')

select *
from IT_MIS_DAILY_FIRST_CALL_REPORT
where DAILY_CONSO=to_date('07/03/2018','dd/mm/yyyy')
and SUBSCRIBER='224662133569'

select *
from it_mis_cellid_final_2013
where cellid='61541'


--HISTORIQUE PAR ZONE----------------
--APPRES LE LANCEMENT DU SPOOL spoolmscevents dans G:\CRS\DR\KPMG\KPMG POUR LA JOURNEE DEMANDEE ET APRES LE CHARGEMENT DES DONNEES DE LOCALISATION DANS LA TABLE TEMPORAIRE----
select SERVED_MSISDN APPELANTS,
       CALLED_NUMBER APPELES,
       SUBSTR(UTC_TIMESTAMP,1,LENGTH(UTC_TIMESTAMP)-1) DATES,
       substr(UTC_TIMESTAMP,12,2) HEURES,
       DURATION DUREE,
       SERVED_IMSI IMSI,
       SERVED_IMEI IMEI,
       GOUVERNORATS LOCALISATION,
       a.CELL_ID CELLULE_ID,
       CELLNAMES CELLULE_NAME,
       VILLE,
       COMMUNES PREFECTURE,
       REGION_NATURELLE REGION,
       LATITUDE,
       LONGITUDE,
       MNC1,
       MNC2,
       LAC,
       CALL_TYPE TYPE
from (
select SERVED_MSISDN,CALLED_NUMBER,UTC_ANSWER_TIME UTC_TIMESTAMP,call_DURATION DURATION,SERVED_IMSI,SERVED_IMEI, decode(TRAFFIC_TYPE_ID,'0','ORIGINATING_CALL','4','ORIGINATING_SMS','200000','TERMINATING_CALL','200004','TERMINATING_SMS') CALL_TYPE,
case when substr(FIRST_CELL_IDENTITY,-5,5) like '-%' then substr(FIRST_CELL_IDENTITY,-4,4)  else substr(FIRST_CELL_IDENTITY,-5,5) end cell_id
from IT_DR_KMPG_MSC_EVENTS_LIVE 
where substr (UTC_ANSWER_TIME,12,2) in ('03','04','05')
and TRAFFIC_TYPE_ID in ('0','4','200000','200004')
) a, MCKINSEY_USER.IT_MK_CELLID_FINAL_2013 b,entag_fassa c
where b.CELLID=a.CELL_ID
and b.CELLID=c.CELL_ID




select CALLING_NUMBER APPELANTS,
       CALLED_NUMBER APPELES,
       UTC_ANSWER_TIME TRANSACTION_DATE,
       CALL_DURATION DUREE,
       SERVED_IMSI IMSI,
       SERVED_IMEI IMEI,
       GOUVERNORATS LOCALISATION,
       case when substr(FIRST_CELL_IDENTITY,-5,5) like '-%' then substr(FIRST_CELL_IDENTITY,-4,4)  else substr(FIRST_CELL_IDENTITY,-5,5) end AS CELLULE_ID,
       CELLNAMES CELLULE_NAME,
       VILLE,
       COMMUNES PREFECTURE,
       REGION_NATURELLE REGION,
       decode(TRAFFIC_TYPE_ID,'0','ORIGINATING_CALL','4','ORIGINATING_SMS','200000','TERMINATING_CALL_ONNET','200004','TERMINATING_SMS_OFFNET' ) CALL_TYPE
from msc_events a, CELLID_FINAL_TEMP b
where (b.CELLID=substr(FIRST_CELL_IDENTITY,-4,4) or b.CELLID=substr(FIRST_CELL_IDENTITY,-5,5)) AND SERVED_MSISDN in ('224664591613','224666702631','224662331978','224669521639')
and TRAFFIC_TYPE_ID in ('0','4','200000','200004')
and to_date(to_char(UTC_ANSWER_TIME,'dd/mm/yyyy'),'dd/mm/yyyy') between   to_date('01/10/2018','dd/mm/yyyy') and to_date('22/01/2019','dd/mm/yyyy')





select SERVED_MSISDN||','||
       CALLED_NUMBER||','||
       decode(TRAFFIC_TYPE_ID,'0','ORIGINATING_CALL','4','ORIGINATING_SMS')||','|| 
       CALL_DURATION||','|| SERVED_IMSI||','|| SERVED_IMEI||','|| case when substr(FIRST_CELL_IDENTITY,-5,5) like '-%' then substr(FIRST_CELL_IDENTITY,-4,4)  else substr(FIRST_CELL_IDENTITY,-5,5) end ||','|| UTC_ANSWER_TIME TRANSACTION_DATE
from msc_events b
where SERVED_IMEI in ('351814097369460')

and TRAFFIC_TYPE_ID in ('0','4')

union all 
 
select CALLING_NUMBER||','||
       CALLED_NUMBER||','|| 
       decode(TRAFFIC_TYPE_ID,'200000','TERMINATING_CALL','200004','TERMINATING_SMS' )||','|| 
       CALL_DURATION||','||SERVED_IMSI||','||SERVED_IMEI ||','|| case when substr(FIRST_CELL_IDENTITY,-5,5) like '-%' then substr(FIRST_CELL_IDENTITY,-4,4)  else substr(FIRST_CELL_IDENTITY,-5,5) end ||','||  UTC_ANSWER_TIME TRANSACTION_DATE
from msc_events b
where SERVED_IMEI in ('351814097369460')
and TRAFFIC_TYPE_ID in ('200000','200004');


--APPRES LE LANCEMENT DU SPOOL spoolmscevents dans G:\CRS\DR\KPMG\KPMG POUR LA JOURNEE DEMANDEE ET APRES LE CHARGEMENT DES DONNEES DE LOCALISATION DANS LA TABLE TEMPORAIRE----
select SERVED_MSISDN APPELANTS,
       CALLED_NUMBER APPELES,
       SUBSTR(UTC_TIMESTAMP,1,LENGTH(UTC_TIMESTAMP)-1) DATES,
       substr(UTC_TIMESTAMP,12,2) HEURES,
       DURATION DUREE,
       SERVED_IMSI IMSI,
       SERVED_IMEI IMEI,
       GOUVERNORATS LOCALISATION,
       a.CELL_ID CELLULE_ID,
       CELLNAMES CELLULE_NAME,
       VILLE,
       COMMUNES PREFECTURE,
       REGION_NATURELLE REGION,
       c.BASE_STATION_LAT_TXT LATITIDE,
       c.BASE_STATION_LONG_TXT LONGITUDE,
       c.BASE_STATION_LAC_CD LAC,
       CALL_TYPE TYPE
from (
select SERVED_MSISDN,CALLED_NUMBER,UTC_ANSWER_TIME UTC_TIMESTAMP,call_DURATION DURATION,SERVED_IMSI,SERVED_IMEI, decode(TRAFFIC_TYPE_ID,'0','ORIGINATING_CALL','4','ORIGINATING_SMS','200000','TERMINATING_CALL','200004','TERMINATING_SMS') CALL_TYPE,
case when substr(FIRST_CELL_IDENTITY,-5,5) like '-%' then substr(FIRST_CELL_IDENTITY,-4,4)  else substr(FIRST_CELL_IDENTITY,-5,5) end cell_id
from IT_DR_KMPG_MSC_EVENTS_LIVE 
where substr (UTC_ANSWER_TIME,12,2) in ('01','02')
and TRAFFIC_TYPE_ID in ('0','4','200000','200004')
) a, MCKINSEY_USER.IT_MK_CELLID_FINAL_2013 b,MDNDIALLO.UMD_BASE_STATION@REPORTDBDBLINK c
where b.CELLID=a.CELL_ID
and lower(b.ville)='kissosso'
and b.NEW_CGI=c.BASE_STATION_ID


select * from MDNDIALLO.UMD_BASE_STATION@REPORTDBDBLINK c

select c.BASE_STATION_LAT_TXT LATITIDE, c.BASE_STATION_LONG_TXT LONGITUDE, c.BASE_STATION_LAC_CD LAC
 from MDNDIALLO.UMD_BASE_STATION@REPORTDBDBLINK c


select * from MCKINSEY_USER.IT_MK_CELLID_FINAL_2013
where lower(ville)='kissosso'