/* LOAD VOICE REVENUE AND USER  */
insert into IT_MIS_MOC_REV_GLOBAL_MTH_SUBS
select SERVED_MSISDN ,
  sum(MOC_ONNET_VOICE_CALL) MOC_ONNET_VOICE_CALL,
  sum(MOC_ONNET_VOICE_DURATION)  MOC_ONNET_VOICE_DURATION,
  sum(MOC_ONNET_VOICE_REV)  MOC_ONNET_VOICE_REV,
  sum(MOC_OFFNET_ORANGE_VOICE_CALL)    MOC_OFFNET_ORANGE_VOICE_CALL,
  sum(MOC_OFFNET_ORANGE_VOICE_DUR)     MOC_OFFNET_ORANGE_VOICE_DUR,
  sum(MOC_OFFNET_ORANGE_VOICE_REV)     MOC_OFFNET_ORANGE_VOICE_REV,
  sum(MOC_OFFNET_CELLCOM_VOICE_CALL)   MOC_OFFNET_CELLCOM_VOICE_CALL,
  sum(MOC_OFFNET_CELLCOM_VOICE_DUR)    MOC_OFFNET_CELLCOM_VOICE_DUR,
  sum(MOC_OFFNET_CELLCOM_VOICE_REV)    MOC_OFFNET_CELLCOM_VOICE_REV,
  sum(MOC_OFFNET_INTERCEL_VOICE_CALL)  MOC_OFFNET_INTERCEL_VOICE_CALL,
  sum(MOC_OFFNET_INTERCELL_VOICE_DUR)  MOC_OFFNET_INTERCELL_VOICE_DUR,
  sum(MOC_OFFNET_INTERCELL_VOICE_REV)  MOC_OFFNET_INTERCELL_VOICE_REV,
  sum(MOC_INTER_VOICE_CALL)   MOC_INTER_VOICE_CALL,
  sum(MOC_INTER_VOICE_DURATION)  MOC_INTER_VOICE_DURATION,
  sum(MOC_INTER_VOICE_REV)   MOC_INTER_VOICE_REV,
  sum(MOC_ONNET_SMS)  MOC_ONNET_SMS,
  sum(MOC_TOTAL_ONNET_SMS)   MOC_TOTAL_ONNET_SMS,
  sum(MOC_OFFNET_SMS) MOC_OFFNET_SMS,
  sum(MOC_TOTAL_OFFNET_SMS)  MOC_TOTAL_OFFNET_SMS,
  sum(MOC_INTER_SMS) MOC_INTER_SMS,
  sum(MOC_TOTAL_INTER_SMS) MOC_TOTAL_INTER_SMS,
  sum(PAYG_GPRS_VOLUME)  PAYG_GPRS_VOLUME,
  sum(PAYG_GPRS_REVENUE)   PAYG_GPRS_REVENUE,
  sum(BUNDLE_GPRS_VOLUME)    BUNDLE_GPRS_VOLUME,
  sum(BUNDLE_GPRS_REVENUE)    BUNDLE_GPRS_REVENUE,
  sum(CONTENT_IMMI_TRANSACTIONS)  CONTENT_IMMI_TRANSACTIONS,
  sum(CONTENT_IMMI_REV)   CONTENT_IMMI_REV,
  sum(CONTENT_SERVICE_TRANSAC)   CONTENT_SERVICE_TRANSACTIONS,
  sum(CONTENT_SERVICE_REV)  CONTENT_SERVICE_REV,  
  to_char(TRANSACTION_DATE,'yyyymm') TRANSACTION_DATE
from IT_MIS_MOC_REV_GLOBAL_MTH17_1 
where to_char(TRANSACTION_DATE,'yyyymm')='201810'
group by SERVED_MSISDN,to_char(TRANSACTION_DATE,'yyyymm');

commit;

/* LOAD DATA REVENUE AND USER  */

insert into IT_MIS_DATA_USER_SUBS
select to_char(TRANSACTION_DATE,'yyyymm') PERIOD,SERVED_MSISDN ,
  sum(PAYG_GPRS_VOLUME)  PAYG_GPRS_VOLUME,
  sum(PAYG_GPRS_REVENUE)   PAYG_GPRS_REVENUE,
  sum(BUNDLE_GPRS_VOLUME)    BUNDLE_GPRS_VOLUME,
  sum(BUNDLE_GPRS_REVENUE)    BUNDLE_GPRS_REVENUE   
from IT_MIS_MOC_REV_GLOBAL_MTH17_1 
where to_char(TRANSACTION_DATE,'yyyymm')='201810'
group by SERVED_MSISDN,to_char(TRANSACTION_DATE,'yyyymm');

commit;

truncate table IT_MIS_DATA_USER_SUBS_RGS90_B4;

insert into IT_MIS_DATA_USER_SUBS_RGS90_B4  
select distinct '201809' PERIOD,SERVED_MSISDN,sum(PAYG_GPRS_VOLUME) PAYG_GPRS_VOLUME,
       sum(PAYG_GPRS_REVENUE) PAYG_GPRS_REVENUE,
       sum(BUNDLE_GPRS_VOLUME) BUNDLE_GPRS_VOLUME,
       sum(BUNDLE_GPRS_REVENUE) BUNDLE_GPRS_REVENUE 
from IT_MIS_DATA_USER_SUBS 
where PERIOD in('201807','201808','201809') 
--and (PAYG_GPRS_VOLUME+BUNDLE_GPRS_VOLUME)> 5242880
group by SERVED_MSISDN;

commit;

insert into IT_MIS_DATA_USER_SUBS_NEW 
select distinct PERIOD,SERVED_MSISDN,PAYG_GPRS_VOLUME,PAYG_GPRS_REVENUE,BUNDLE_GPRS_VOLUME,BUNDLE_GPRS_REVENUE 
from IT_MIS_DATA_USER_SUBS 
where PERIOD ='201810'
and (PAYG_GPRS_VOLUME+BUNDLE_GPRS_VOLUME)>= 5242880
AND SERVED_MSISDN not in(
                        select SERVED_MSISDN--,PAYG_GPRS_VOLUME,PAYG_GPRS_REVENUE,BUNDLE_GPRS_VOLUME,BUNDLE_GPRS_REVENUE 
                        from IT_MIS_DATA_USER_SUBS_RGS90_B4 
                        where (PAYG_GPRS_VOLUME+BUNDLE_GPRS_VOLUME)<= 5242879);
                        
commit;


/* IMEI GROSS ADD  */

select to_date(to_char(PROVISION_DATE,'dd/mm/yyyy'),'dd/mm/yyyy') PROVISION_DATE,count(distinct IMEI) IMEI_GADD,
round((count(distinct IMEI))/(select count(distinct IMEI) IMEI_Loaded from IT_IMEI_MSISDN_DMC)*100,2) IMEI_GADD_PCT
from IT_IMEI_MSISDN_DMC 
where PROVISION_DATE is not null 
group by to_date(to_char(PROVISION_DATE,'dd/mm/yyyy'),'dd/mm/yyyy')


--------VOICE

select PERIOD,sum(VOICE_REVENUE) VOICE_REVENUE,count(distinct msisdn) Voice_User
from
(
select distinct to_char(PROVISION_DATE,'yyyymm') PROVISION_DATE, substr(DMC_MSISDN,2,12) msisdn 
from IT_IMEI_MSISDN_DMC where PROVISION_DATE is not null 
) a,
(
select PERIOD,SERVED_MSISDN SERVED_MSISDN,
MOC_ONNET_VOICE_REV+MOC_OFFNET_ORANGE_VOICE_REV+MOC_OFFNET_CELLCOM_VOICE_REV+MOC_OFFNET_INTERCELL_VOICE_REV+MOC_INTER_VOICE_REV  VOICE_REVENUE
from IT_MIS_MOC_REV_GLOBAL_MTH_SUBS
WHERE (MOC_ONNET_VOICE_REV+MOC_OFFNET_ORANGE_VOICE_REV+MOC_OFFNET_INTERCELL_VOICE_REV+MOC_INTER_VOICE_REV)>=0 
) b
where msisdn=SERVED_MSISDN
and PERIOD=PROVISION_DATE
group by PERIOD



--------DATA

select PERIOD,count(distinct MSISDN) DATA_USER,
       round(count(distinct MSISDN)/39966*100,2) DATA_USER_PCT, --(select count(distinct IMEI) from IT_IMEI_MSISDN_DMC)*100,2) DATA_USER_PCT
       sum(PAYG_GPRS_REVENUE+BUNDLE_GPRS_REVENUE) x
from
(
select distinct to_char(PROVISION_DATE,'yyyymm') PROVISION_DATE,substr(DMC_MSISDN,2,12) msisdn 
from IT_IMEI_MSISDN_DMC where PROVISION_DATE is not null 
) a,
(
select * from IT_MIS_DATA_USER_SUBS 
) b
where msisdn=SERVED_MSISDN
and PERIOD=PROVISION_DATE
group by PERIOD


/* NEW DATA USER */
select PERIOD,count(distinct MSISDN) NEW_DATA_USER,
       round(count(distinct MSISDN)/39966*100,2) NEW_DATA_USER_PCT, --(select count(distinct IMEI) from IT_IMEI_MSISDN_DMC)*100,2) DATA_USER_PCT
       sum(PAYG_GPRS_REVENUE+BUNDLE_GPRS_REVENUE) x
from
(
select distinct to_char(PROVISION_DATE,'yyyymm') PROVISION_DATE,substr(DMC_MSISDN,2,12) msisdn 
from IT_IMEI_MSISDN_DMC where PROVISION_DATE is not null 
) a,
(
select * from IT_MIS_DATA_USER_SUBS_NEW where PERIOD='201810' and (PAYG_GPRS_VOLUME+BUNDLE_GPRS_VOLUME)>= 5242880 
) b
where msisdn=SERVED_MSISDN
and PERIOD=PROVISION_DATE
group by PERIOD


/* NEW DATA BUNDLE USER */
select PERIOD,count(distinct MSISDN) NEW_DATA_BUNDLE_USER,
       round(count(distinct MSISDN)/39966*100,2) NEW_DATA_BUNDLE_USER_PCT, --(select count(distinct IMEI) from IT_IMEI_MSISDN_DMC)*100,2) DATA_USER_PCT
       sum(PAYG_GPRS_REVENUE+BUNDLE_GPRS_REVENUE) x
from
(
select distinct to_char(PROVISION_DATE,'yyyymm') PROVISION_DATE,substr(DMC_MSISDN,2,12) msisdn 
from IT_IMEI_MSISDN_DMC where PROVISION_DATE is not null 
) a,
(
select * from IT_MIS_DATA_USER_SUBS_NEW where PERIOD='201810' and BUNDLE_GPRS_VOLUME>= 5242880 
) b
where msisdn=SERVED_MSISDN
and PERIOD=PROVISION_DATE
group by PERIOD
