CREATE TABLE IT_MIS_AGING_MSISDN_MAX80 AS
select SERVED_MSISDN,MAX(UTC_TIMESTAMP) MAX_UTC_TIMESTAMP
from report_user.IT_MIS_USAGE_EVENTS_DTL_12  partition(D20180601_USAGE_EVENTS)
where SERVED_MSISDN in(SELECT MSISDN FROM IT_MIS_AGING_MSISDN_CHECK where AGING_DATE=80)
group by SERVED_MSISDN

select MSISDN FROM report_user.IT_MIS_AGING_MSISDN_CHECK
where AGING_DATE=81


from MSC_EVENTS partition(D20180531_MSC_EVENTS)
where SERVED_MSISDN in (select MSISDN FROM report_user.IT_MIS_AGING_MSISDN_CHECK
where AGING_DATE=80)

