SELECT INITIATOR_MSISDN, sum(AMOUNT), substr(TRANSACTION_DATE,1,7) TRANSACTION_DATE,
       CASE WHEN TRANSACTION_DATE like'D201807%' THEN 'JUL'
            WHEN TRANSACTION_DATE like'D201808%' THEN 'AUG'
            WHEN TRANSACTION_DATE like'D201809%' THEN 'SEPT'
FROM 

create table taf_taf_trans as
select 'D20180901' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180901_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'

SELECT INITIATOR_MSISDN, sum(AMOUNT) AMOUNT, substr(TRANSACTION_DATE,1,7) TRANSACTION_DATE
FROM taf_taf_trans
GROUP BY INITIATOR_MSISDN, substr(TRANSACTION_DATE,1,7),TRANSACTION_DATE



insert into taf_taf_trans
select 'D20180902' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180902_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180903' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180903_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180904' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180904_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180905' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180905_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180906' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180906_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180907' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180907_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180908' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180908_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180909' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180909_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180910' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180910_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180911' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180911_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180912' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180912_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180913' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180913_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180914' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180914_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180915' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180915_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180916' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180916_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180917' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180917_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180918' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180918_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180919' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180919_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180920' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180920_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180921' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180921_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180922' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180922_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180923' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180923_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180924' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180924_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180925' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180925_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180801' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180801_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180802' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180802_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180803' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180803_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180804' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180804_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180805' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180805_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180806' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180806_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180807' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180807_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180808' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180808_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180809' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180809_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180810' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180810_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180811' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180811_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180812' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180812_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180813' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180813_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180814' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180814_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180815' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180815_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180816' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180816_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180817' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180817_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180818' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180818_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180819' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180819_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180820' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180820_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180821' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180821_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180822' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180822_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180823' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180823_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180824' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180824_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180825' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180825_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180826' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180826_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180827' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180827_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180828' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180828_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180829' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180829_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180830' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180830_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180831' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180831_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180701' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180701_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180702' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180702_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180703' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180703_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180704' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180704_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180705' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180705_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180706' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180706_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180707' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180707_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180708' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180708_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180709' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180709_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180710' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180710_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180711' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180711_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180712' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180712_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180713' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180713_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180714' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180714_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180715' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180715_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180716' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180716_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180717' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180717_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180718' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180718_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180719' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180719_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180720' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180720_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180721' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180721_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180722' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180722_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180723' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180723_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180724' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180724_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180725' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180725_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180726' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180726_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180727' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180727_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180728' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180728_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180729' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180729_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180730' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180730_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180731' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180731_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit;



GROUP BY INITIATOR_MSISDN,TRANSACTION_DATE