BEGIN

DECLARE

filename VARCHAR2(50);

CURSOR cursor_table IS 

SELECT   NAME,SUBSTR(NAME,1,2) day_name,TO_CHAR(TO_DATE(NAME,'dd/mm/yyyy'),'yyyymmdd') day_name2
FROM IT_DAY_TO_DAY
-- WHERE TO_DATE(NAME,'dd/mm/yyyy') BETWEEN TO_DATE('16/10/2015','dd/mm/yyyy') AND TO_DATE('16/10/2015','dd/mm/yyyy') 
--to_date('05/04/2014','dd/mm/yyyy') and  to_date('09/04/2014','dd/mm/yyyy')
WHERE TO_DATE(NAME,'dd/mm/yyyy') BETWEEN to_date(to_char(sysdate-1,'dd/mm/yyyy'),'dd/mm/yyyy') and  to_date(to_char(sysdate-1,'dd/mm/yyyy'),'dd/mm/yyyy')
ORDER BY SUBSTR(NAME,1,2) ;


record_cursor_table    cursor_table%ROWTYPE;

BEGIN 
  
  OPEN cursor_table;
       
     LOOP
         FETCH cursor_table INTO record_cursor_table;
            EXIT WHEN cursor_table%NOTFOUND; 
            

            SELECT 'USAGE_EVENTS_CRS_'||record_cursor_table.day_name2||'.csv' INTO filename
            FROM dual;         
                           
            EXECUTE IMMEDIATE ' alter table USAGE_EVENTS_CRS2  '||' location('''||filename||''')';   
            
--            SELECT 'MTC_EVENTS_CRS_'||record_cursor_table.day_name2||'.csv' INTO filename
--            FROM dual;         
--                           
--            EXECUTE IMMEDIATE ' alter table IT_MIS_MTC_CALL_CELLID2 '||' location('''||filename||''')';   


-----------  START MOC  --------------- 

        EXECUTE IMMEDIATE ' truncate table USAGE_EVENTS_CRS_TMP2 ';

        INSERT INTO  USAGE_EVENTS_CRS_TMP2 
        SELECT  SERVED_MSISDN,LAST_CELL_IDENTITY CELLID,SUM(REPLACE(TOTAL_COST,',','.')) TOTAL_COST,TO_DATE(SUBSTR(UTC_TIMESTAMP,1,10),'dd/mm/yyyy') report_date
        FROM USAGE_EVENTS_CRS2
      --  where LAST_CELL_IDENTITY is not null
        GROUP BY SERVED_MSISDN,LAST_CELL_IDENTITY,TO_DATE(SUBSTR(UTC_TIMESTAMP,1,10),'dd/mm/yyyy');

        COMMIT;
 

--- DELETE MAJOR CELLID FOR THE PREVIOUS DAY AFTER ARCHIVING INTO THE MOC MONTHLY TABLE  

      EXECUTE IMMEDIATE ' truncate table IT_MIS_MOC_MJR_CELLID_DAILY2 ';        
        
     COMMIT;
        
---- MAJOR CELLID OF EACH MSISDN  WITH MAJOR CELLID AND TOTAL  REVENUE PER DAY       

 INSERT INTO IT_MIS_MOC_MJR_CELLID_DAILY2
 
 SELECT  t1.SERVED_MSISDN,t1.MAJOR_CELLID,t1.MAJOR_CELLID_VOICE_REV,t2.total_cost TOTAL_VOICE_REV, t1.report_date
        FROM 
        ( 
          ---- MAJOR CELLID OF EACH MSISDN  WITH ITS REVENUE PER DAY  
        SELECT a.SERVED_MSISDN,MAJOR_CELLID,TOTAL_COST MAJOR_CELLID_VOICE_REV,a.report_date
        FROM 
        ( ---MAJOR CELLID OF EACH MSISDN PER DAY 
                SELECT  SERVED_MSISDN,MAX(CELLID) MAJOR_CELLID,report_date
                FROM ( SELECT * FROM USAGE_EVENTS_CRS_TMP2
                     ) t1
                WHERE t1.TOTAL_COST = ( SELECT MAX(TOTAL_COST) TOTAL_COST
                                      FROM ( SELECT * FROM USAGE_EVENTS_CRS_TMP2
                                           ) t2  
                                       WHERE t2.report_date=t1.report_date
                                       AND  t2.served_msisdn=t1.served_msisdn
                                      )
                GROUP BY SERVED_MSISDN,report_date 
                
              ) a, USAGE_EVENTS_CRS_TMP2 b 
        WHERE a.MAJOR_CELLID=b.CELLID 
        AND a.served_msisdn=b.served_msisdn
        AND a.report_date=b.report_date   ) t1, ( --- TOTAL REVENUE GENERATED BY MSISDN 
                                                SELECT  served_msisdn,SUM(total_cost) total_cost ,report_date 
                                                FROM  USAGE_EVENTS_CRS_TMP2
                                                GROUP BY  served_msisdn,report_date 
                                               ) t2
        WHERE t1.served_msisdn=t2.served_msisdn
        AND  t1.report_date=t2.report_date;

        COMMIT;
        
        

        END LOOP;  
        
               CLOSE cursor_table;
                   
END;


END;
/

BEGIN 

DECLARE


    CONETNT_TOTAL       NUMBER;
    GPRS_TOTAL          NUMBER;
    SMS_TOTAL           NUMBER;
    MOC_TOTAL           NUMBER;

    CONTENT_AREA        NUMBER;
    GPRS_AREA           NUMBER;
    SMS_AREA            NUMBER;
    TOTAL_USAGE_AREA    NUMBER;

    CONETNT_DIFF       NUMBER;
    GPRS_DIFF          NUMBER;
    SMS_DIFF           NUMBER;
    MOC_DIFF           NUMBER;


    CURSOR cursor_table IS 

    SELECT  a.NAME,SUBSTR(a.NAME,1,2) day_name, to_char(to_date(a.name,'dd/mm/yyyy'),'yyyymmdd') day_name2,substr(b.FULL_NAMES_ENGLISH,1,3)||substr(b.YEARS,-2,2) MONTHS
    FROM IT_DAY_TO_DAY a,IT_MONTH_TO_YEAR b
    where substr(a.name,-4,4)=b.YEARS
    AND trim(to_char(to_date(a.name,'dd/mm/yyyy'),'MONTH'))=trim(b.FULL_NAMES_ENGLISH)
    and to_date(a.name,'dd/mm/yyyy')  between to_date(to_char(sysdate-1,'dd/mm/yyyy'),'dd/mm/yyyy') and to_date(to_char(sysdate-1,'dd/mm/yyyy'),'dd/mm/yyyy') 
    --where to_date(name,'dd/mm/yyyy')  between  to_date('01/11/2017','dd/mm/yyyy') and to_date('27/11/2017','dd/mm/yyyy') 
    order by substr(a.name,1,2) ;
    
    


--    --TO_DATE(TO_CHAR(SYSDATE-2,'dd/mm/yyyy'),'dd/mm/yyyy') AND TO_DATE(TO_CHAR(SYSDATE-2,'dd/mm/yyyy'),'dd/mm/yyyy')
--       
    record_cursor_table    cursor_table%ROWTYPE;

BEGIN 

  OPEN cursor_table;
       
     LOOP
         FETCH cursor_table INTO record_cursor_table;
            EXIT WHEN cursor_table%NOTFOUND;


    EXECUTE IMMEDIATE 'ALTER  TABLE IT_MIS_MJR_CELLID_DAILY_'||record_cursor_table.MONTHS||' TRUNCATE PARTITION(MK'||record_cursor_table.day_name2||')';

COMMIT;
  
EXECUTE IMMEDIATE  'insert into REPORT_USER.IT_MIS_MJR_CELLID_DAILY_'||record_cursor_table.MONTHS||' ' ||
        --- MAJOR CELLID  FOR CONTENT,SMS, GPRS AND VOICE PER MSISDN AND DATE 
        'select  a.SERVED_MSISDN, CONTENT_REV,GPRS_REVENUE, SMS_REV,MAJOR_CELLID,MAJOR_CELLID_VOICE_REV,TOTAL_VOICE_REV,REPORT_DATE  ' ||
        'from  IT_MIS_MOC_MJR_CELLID_DAILY2 a, ' ||
                                                 ' ( select SERVED_MSISDN, ' ||
                                                          'sum(CONTENT_IMMI_REV) + sum(CONTENT_RBT_REV) + sum(CONTENT_MMS_REV)+ sum(CONTENT_MAGIC_VOICE_REV) CONTENT_REV, ' ||
                                                          ' sum(GPRS_REVENUE) GPRS_REVENUE, ' ||
                                                          'sum(MOC_ONNET_SMS)+sum(MOC_OFFNET_SMS)+sum(MOC_INTER_SMS) SMS_REV, ' ||
                                                          'TRANSACTION_DATE  ' || 
                                                 'from   report_user.IT_MIS_MOC_REV_GLOBAL_'||record_cursor_table.MONTHS||' partition (D'||record_cursor_table.day_name2||'_CONSO_VOICE_SMS)   ' ||
                                                 'group by SERVED_MSISDN,TRANSACTION_DATE ' ||
                                                  
                                                '  ) b ' ||
         'where a.served_msisdn=b.SERVED_MSISDN ' ||
        'and a.REPORT_DATE=TRANSACTION_DATE'; --  and a.MAJOR_CELLID not like''%-%''

                  
                    commit;
                    


        
  /* SCRIPT LOAD GPRS LOCALIZED */        
EXECUTE IMMEDIATE  ' insert into IT_MIS_MJR_CELLID_DAILY_'||record_cursor_table.MONTHS||' ' || 
                   'select a.SERVED_MSISDN,0,a.TOTAL_GPRS_REV,0,a.MAJOR_CELLID,0,0,a.REPORT_DATE from REPORT_USER.IT_MIS_GPRS_MJR_CELLID_DAILY1 a ' ||
                   'where a.REPORT_DATE=to_date('||record_cursor_table.day_name2||',''yyyy/mm/dd'')' ||
                   'and  a.SERVED_MSISDN not in(select MSISDN from IT_MIS_MJR_CELLID_DAILY_'||record_cursor_table.MONTHS||' partition(MK'||record_cursor_table.day_name2||'))'; --  and a.MAJOR_CELLID not like''%-%''
            commit; 
            
            ---- 
            /*EXECUTE IMMEDIATE  ' insert into IT_MIS_MJR_CELLID_DAILY_DEC17 ' || 
                   'select a.SERVED_MSISDN,0,a.TOTAL_GPRS_REV,0,a.MAJOR_CELLID,0,0,a.REPORT_DATE from REPORT_USER.IT_MIS_GPRS_MJR_CELLID_DAILY1 a ' ||
                   'where a.REPORT_DATE=to_date('||record_cursor_table.day_name2||',''yyyy/mm/dd'')' ||
                   'and  a.SERVED_MSISDN not in(select MSISDN from IT_MIS_MJR_CELLID_DAILY_DEC17 partition(MK'||record_cursor_table.day_name2||')) and a.MAJOR_CELLID not like''%-%''';
            commit;
            
             REGEXP_SUBSTR (MAJOR_CELLID, '[^-]+')||SUBSTR((MAJOR_CELLID),-(length(MAJOR_CELLID)-(length(REGEXP_SUBSTR (MAJOR_CELLID, '[^-]+'))+1)),(length(MAJOR_CELLID)-(length(REGEXP_SUBSTR (MAJOR_CELLID, '[^-]+'))+1)))*/
            ----
            /* SCRIPT LOAD FC ACTIVATION LOCALIZED VIA AXON */ /* 
           insert into IT_MIS_MJR_CELLID_DAILY_DEC17 
            SELECT a.CUSTOMER_MSISDN,0,0,0,a.CELLID,0,0,a.REPORT_DATE FROM IT_MIS_FC_CELLID_AXON_ACTIVATE a
            where a.REPORT_DATE=to_date(to_char(sysdate-1,'dd/mm/yyyy'),'dd/mm/yyyy')
            and  a.CUSTOMER_MSISDN not in(select MSISDN from IT_MIS_MJR_CELLID_DAILY_DEC17 partition(MK20170408));
            commit; 
            
            */
EXECUTE IMMEDIATE  ' insert into IT_MIS_MJR_CELLID_DAILY_'||record_cursor_table.MONTHS||' ' || 
                   'SELECT a.CUSTOMER_MSISDN,0,0,0,a.CELLID,0,0,a.REPORT_DATE FROM IT_MIS_FC_CELLID_AXON_ACTIVATE a ' ||
                   'where a.REPORT_DATE=to_date('||record_cursor_table.day_name2||',''yyyy/mm/dd'')' ||
                   'and  a.CUSTOMER_MSISDN not in(select MSISDN from IT_MIS_MJR_CELLID_DAILY_'||record_cursor_table.MONTHS||' partition(MK'||record_cursor_table.day_name2||'))'; --  and a.CELLID not like''%-%''
            commit;  
            
        delete from IT_MIS_MJR_CELLID_DAILY_PPAID 
        where TRANSACTION_DATE=to_date(record_cursor_table.name,'dd/mm/yyyy');

        commit;

        execute immediate 'insert into IT_MIS_MJR_CELLID_DAILY_PPAID '|| 
        'select * from IT_MIS_MJR_CELLID_DAILY_'||record_cursor_table.MONTHS||' partition  (MK'||record_cursor_table.day_name2||') a where substr(a.MSISDN,4,9) in(select ACCOUNT_MSISDN from IT_DR_IN_STATUS_SUBSCRIBERS where ACCOUNT_CLASS=''80'')';

        commit; 

        execute immediate 'delete from IT_MIS_MJR_CELLID_DAILY_'||record_cursor_table.MONTHS||' partition  (MK'||record_cursor_table.day_name2||') a where substr(a.MSISDN,4,9) in(select ACCOUNT_MSISDN from IT_DR_IN_STATUS_SUBSCRIBERS where ACCOUNT_CLASS=''80'')';

        commit; 
            
        delete from   IT_MIS_CONSO_SMSCONTGPRS_AREA
        where TRANSACTION_DATE=to_date(record_cursor_table.day_name2,'yyyy/mm/dd'); --   BETWEEN TO_DATE('22/01/2015','dd/mm/yyyy') AND TO_DATE('22/01/2015','dd/mm/yyyy');
        -- and VILLE = 'UNKNOWN';
        commit;
        
       EXECUTE IMMEDIATE  'insert into  REPORT_USER.IT_MIS_CONSO_SMSCONTGPRS_AREA ' ||
                            'select to_number(a.MAJOR_CELLID),b.CELLCODE,b.SITE_NAMES,b.CELLNAMES,decode(b.SITE_TYPE,''2G'',b.CAP_CELID_2G,b.CAP_CELID_3G) CAP_CELID, b.VILLE, b.GOUVERNORATS,b.REGION_NATURELLE, sum(CONTENT_REV) CONTENT_REV ,sum(GPRS_REVENUE) GPRS_REVENUE ,sum(SMS_REV) SMS_REV ,sum(TOTAL_USAGE) TOTAL_USAGE,TRANSACTION_DATE ' || 
                            'from  ( ' ||
                            'select ''MCKINSEY_REPORT'' REPORT_TYPE, sum(CONTENT_REV) CONTENT_REV , sum(GPRS_REVENUE) GPRS_REVENUE , sum(SMS_REV) SMS_REV ,sum(TOTAL_VOICE_REV) TOTAL_USAGE ,MAJOR_CELLID,TRANSACTION_DATE ' ||
                            'from REPORT_USER.IT_MIS_MJR_CELLID_DAILY_'||record_cursor_table.MONTHS||' partition  (MK'||record_cursor_table.day_name2||') where  MAJOR_CELLID not like''%-%'' '|| 
                            'group by  MAJOR_CELLID,TRANSACTION_DATE  ) a , REPORT_USER.IT_MIS_CELLID_FINAL_2013 b ' ||
                            'where a.MAJOR_CELLID=b.CELLID(+) ' ||
                            'group by a.MAJOR_CELLID, b.CELLCODE,b.SITE_NAMES,b.CELLNAMES,decode(b.SITE_TYPE,''2G'',b.CAP_CELID_2G,b.CAP_CELID_3G), b.VILLE, b.GOUVERNORATS,b.REGION_NATURELLE,TRANSACTION_DATE ' ;
                             
                            commit;
 
        
        EXECUTE IMMEDIATE  'insert into  REPORT_USER.IT_MIS_CONSO_SMSCONTGPRS_AREA ' ||
                            'select to_number(trim(b.CODE_COUNTRY_OPERATOR)),b.ROAMING_PARTNER_NAME||''/''||b.VPMN_COUNTRY_NAME CELLCODE,b.ROAMING_PARTNER_NAME||''/''||b.VPMN_COUNTRY_NAME SITE_NAMES,b.ROAMING_PARTNER_NAME||''/''||b.VPMN_COUNTRY_NAME CELLNAMES,''NA'' CAP_CELID, b.ROAMING_PARTNER_NAME||''/''||b.VPMN_COUNTRY_NAME VILLE, b.ROAMING_PARTNER_NAME||''/''||b.VPMN_COUNTRY_NAME GOUVERNORATS,b.ROAMING_PARTNER_NAME||''/''||b.VPMN_COUNTRY_NAME REGION_NATURELLE, sum(CONTENT_REV) CONTENT_REV ,sum(GPRS_REVENUE) GPRS_REVENUE ,sum(SMS_REV) SMS_REV ,sum(TOTAL_USAGE) TOTAL_USAGE,TRANSACTION_DATE ' || 
                            'from  ( ' ||
                            'select ''MCKINSEY_REPORT'' REPORT_TYPE, sum(CONTENT_REV) CONTENT_REV , sum(GPRS_REVENUE) GPRS_REVENUE , sum(SMS_REV) SMS_REV ,sum(TOTAL_VOICE_REV) TOTAL_USAGE , ' ||
                            'REGEXP_SUBSTR (MAJOR_CELLID, ''[^-]+'')||SUBSTR((MAJOR_CELLID),-(length(MAJOR_CELLID)-(length(REGEXP_SUBSTR (MAJOR_CELLID, ''[^-]+''))+1)),(length(MAJOR_CELLID)-(length(REGEXP_SUBSTR (MAJOR_CELLID, ''[^-]+''))+1))) MAJOR_CELLID, ' ||
                            'TRANSACTION_DATE ' ||
                            'from REPORT_USER.IT_MIS_MJR_CELLID_DAILY_'||record_cursor_table.MONTHS||' partition  (MK'||record_cursor_table.day_name2||') where  MAJOR_CELLID like''%-%'' '|| 
                            'group by  MAJOR_CELLID,TRANSACTION_DATE  ) a , REPORT_USER.IT_ROAMING_PARTNER_IMSI b ' ||
                            'where substr(a.MAJOR_CELLID,1,5)=substr(trim(b.CODE_COUNTRY_OPERATOR(+)),1,5) ' ||
                            'group by to_number(trim(b.CODE_COUNTRY_OPERATOR)), b.ROAMING_PARTNER_NAME||''/''||b.VPMN_COUNTRY_NAME,TRANSACTION_DATE ' ;
                             
                            commit;
                            
        
            select CONETNT_REVENUE into CONETNT_TOTAL 
            from REPORT_USER.IT_MIS_CRS_REV_GLOBAL_REPORT
            where to_date(dates_hour,'dd/mm/yyyy') = to_date(record_cursor_table.day_name2,'yyyy/mm/dd');
                

            select GPRS_REVENUE into GPRS_TOTAL 
            from REPORT_USER.IT_MIS_CRS_REV_GLOBAL_REPORT
            where to_date(dates_hour,'dd/mm/yyyy') = to_date(record_cursor_table.day_name2,'yyyy/mm/dd');
                

            select SMS_REVENUE into SMS_TOTAL 
            from REPORT_USER.IT_MIS_CRS_REV_GLOBAL_REPORT
            where to_date(dates_hour,'dd/mm/yyyy') = to_date(record_cursor_table.day_name2,'yyyy/mm/dd');
                
            select MOC_REVENUE into MOC_TOTAL 
            from REPORT_USER.IT_MIS_CRS_REV_GLOBAL_REPORT
            where to_date(dates_hour,'dd/mm/yyyy') = to_date(record_cursor_table.day_name2,'yyyy/mm/dd');


            select nvl(sum(CONTENT_REV),0) into CONTENT_AREA
            from   REPORT_USER.IT_MIS_CONSO_SMSCONTGPRS_AREA
            where TRANSACTION_DATE = to_date(record_cursor_table.day_name2,'yyyy/mm/dd');

            select nvl(sum(GPRS_REVENUE),0) into GPRS_AREA
            from   REPORT_USER.IT_MIS_CONSO_SMSCONTGPRS_AREA
            where TRANSACTION_DATE = to_date(record_cursor_table.day_name2,'yyyy/mm/dd');

            select nvl(sum(SMS_REV),0) into SMS_AREA
            from   REPORT_USER.IT_MIS_CONSO_SMSCONTGPRS_AREA
            where TRANSACTION_DATE = to_date(record_cursor_table.day_name2,'yyyy/mm/dd');

            select nvl(sum(TOTAL_USAGE),0) into TOTAL_USAGE_AREA
            from   REPORT_USER.IT_MIS_CONSO_SMSCONTGPRS_AREA
            where TRANSACTION_DATE = to_date(record_cursor_table.day_name2,'yyyy/mm/dd');


            select CONETNT_TOTAL - CONTENT_AREA INTO CONETNT_DIFF FROM DUAL;--,GPRS_TOTAL - GPRS_AREA INTO GPRS_DIFF,SMS_TOTAL - SMS_AREA INTO SMS_DIFF,TOTAL_USAGE_TOTAL - TOTAL_USAGE_AREA INTO TOTAL_USAGE_DIFF 
            select GPRS_TOTAL - GPRS_AREA INTO GPRS_DIFF FROM DUAL;
            select SMS_TOTAL - SMS_AREA INTO SMS_DIFF FROM DUAL;
            select MOC_TOTAL - TOTAL_USAGE_AREA INTO MOC_DIFF FROM DUAL;

 
      /*  delete from   REPORT_USER.IT_MIS_CONSO_SMSCONTGPRS_AREA
        where TRANSACTION_DATE = to_date(record_cursor_table.day_name2,'yyyy/mm/dd')
        and VILLE = 'UNKNOWN';
        commit; */
        
            insert into REPORT_USER.IT_MIS_CONSO_SMSCONTGPRS_AREA
            select '0','UNKNOWN','UNKNOWN','UNKNOWN','0','UNKNOWN','UNKNOWN','UNKNOWN',CONETNT_DIFF,GPRS_DIFF,SMS_DIFF,MOC_DIFF,to_date(record_cursor_table.day_name2,'yyyy/mm/dd')
            from dual;
            commit;
            
            delete from   IT_MIS_CONSO_SMSCONTGPRS_AREA
            where TRANSACTION_DATE=to_date(record_cursor_table.day_name2,'yyyy/mm/dd') --   BETWEEN TO_DATE('22/01/2015','dd/mm/yyyy') AND TO_DATE('22/01/2015','dd/mm/yyyy');
            and CONTENT_REV = 0 and GPRS_REVENUE = 0 and SMS_REV = 0 and TOTAL_USAGE = 0;
            
        commit;
        
        delete from   IT_MIS_CONSO_SMSCONTGPRS_AREA@MKDBLINK
        where TRANSACTION_DATE = to_date(record_cursor_table.day_name2,'yyyy/mm/dd');
        --and VILLE = 'UNKNOWN';
        commit;
        
        insert into  IT_MIS_CONSO_SMSCONTGPRS_AREA@MKDBLINK
        select * from   REPORT_USER.IT_MIS_CONSO_SMSCONTGPRS_AREA
        where TRANSACTION_DATE = to_date(record_cursor_table.day_name2,'yyyy/mm/dd');
        commit;
        
        
       END LOOP;  
               CLOSE cursor_table;
       
     END; 
  

END;
/
