exec REPORT_USER.IT_MIS_GADD_DEL_4_REGUL1;
exec REPORT_USER.IT_MIS_TRACKING_FC_NEW_TMP; 

DELETE FROM IT_MK_DAILY_FC_REPART_GLOBAL@MKDBLINK p
WHERE p.ACTIVATION_DATE BETWEEN to_date('17/07/2018','dd/mm/yyyy') and to_date('17/07/2018','dd/mm/yyyy');

COMMIT;

insert into IT_MK_DAILY_FC_REPART_GLOBAL@MKDBLINK
select * FROM REPORT_USER.IT_MIS_DAILY_FC_REPART_GLOBAL p
WHERE p.ACTIVATION_DATE BETWEEN to_date('17/07/2018','dd/mm/yyyy') and to_date('17/07/2018','dd/mm/yyyy');

COMMIT;

DELETE FROM IT_MK_DAILY_FISRT_CALL_GLOBAL@MKDBLINK k
WHERE k.ACTIVATION_DATE BETWEEN to_date('17/07/2018','dd/mm/yyyy') and to_date('17/07/2018','dd/mm/yyyy');

COMMIT; 

insert into IT_MK_DAILY_FISRT_CALL_GLOBAL@MKDBLINK
select * FROM REPORT_USER.IT_MIS_DAILY_FISRT_CALL_GLOBAL k
WHERE k.ACTIVATION_DATE BETWEEN to_date('17/07/2018','dd/mm/yyyy') and to_date('17/07/2018','dd/mm/yyyy');

COMMIT; 

DELETE FROM IT_MK_DAILY_FIRST_CALL_BALANC2@MKDBLINK
WHERE daily_conso BETWEEN to_date('17/07/2018','dd/mm/yyyy') and to_date('17/07/2018','dd/mm/yyyy');

COMMIT;

insert into IT_MK_DAILY_FIRST_CALL_BALANC2@MKDBLINK
select * FROM REPORT_USER.IT_MK_DAILY_FIRST_CALL_BALANC2
WHERE daily_conso BETWEEN to_date('17/07/2018','dd/mm/yyyy') and to_date('17/07/2018','dd/mm/yyyy');

COMMIT;
