-----SCRIPTS D'ANNULATION DE LIVRAISON DANS LA BASE DE DONNEES PHEB 

USE MTN_SOCIETE_01
SELECT * FROM dbo.ACH_COMMANDE 
WHERE dbo.ACH_COMMANDE.ACT_NUMERO='8CO00351' -- in('8CO00351','8CO00549')

update dbo.ACH_COMMANDE
set ACT_LIV_ETAT=0
WHERE dbo.ACH_COMMANDE.ACT_NUMERO='8CO00351' 
and ACT_LIV_ETAT!=0

