--MCKINSEY--------------------

--INTERCO VOICE---------------
select NDC,TOTAL,AMOUNT,REPORT_DATE
from MCKINSEY_USER.INTERCO_SMS_VOICE_DAILY
where TYPE like'%VOICE%'
and REPORT_DATE between '20180601' and '20180831'
order by REPORT_DATE

--INTERCO SMS-----------------
select NDC,TOTAL,AMOUNT,REPORT_DATE
from MCKINSEY_USER.INTERCO_SMS_VOICE_DAILY
where TYPE like'%SMS%'
and REPORT_DATE between '20180601' and '20180831'
order by REPORT_DATE




--REPORTDB--------------------

--ROAMING VOICE---------------
select REPORT_DATE,TRANSACTION_TYPE,OPACCUMSEC+PACCUMSEC,OPUNITS+OPUNITS
from report_user.IT_MIS_CRS_REV_MONTHLY_FINAL3
where TRANSACTION_TYPE IN('CAPV2 MOC ROAMING','CAPV2 MTC ROAMING') -- TRANSACTION_TYPE like'%SMS ROAMING%'
and REPORT_DATE between '20180601' and '20180831'

--ROAMING SMS-----------------
select REPORT_DATE,TRANSACTION_TYPE,OPCALLS+PCALLS TOTAL,OPUNITS+OPUNITS REVENUE
from report_user.IT_MIS_CRS_REV_MONTHLY_FINAL3
where TRANSACTION_TYPE like'%SMS ROAMING%'
and REPORT_DATE between '20180601' and '20180831'