CREATE TABLESPACE work_space DATAFILE 'D:\DATAfile\file.dbf' SIZE 2048M
   AUTOEXTEND ON
   EXTENT MANAGEMENT LOCAL
   SEGMENT SPACE MANAGEMENT AUTO;

   CREATE USER Mdian 
    IDENTIFIED BY Mddiari93 
    DEFAULT TABLESPACE work_space 
    TEMPORARY TABLESPACE TEMP 
    PROFILE DEFAULT 
    ACCOUNT UNLOCK;
	
GRANT CONNECT TO Mdian;
GRANT CONNECT, RESOURCE, DBA TO Mdian;
GRANT CREATE SESSION TO Mdian;
GRANT CREATE ANY TABLE TO Mdian;
GRANT UPDATE ANY TABLE TO Mdian;
GRANT INSERT ANY TABLE TO Mdian;
GRANT SELECT ANY TABLE TO Mdian;
GRANT DELETE ANY TABLE TO Mdian;
GRANT UNLIMITED TABLESPACE TO Mdian;
GRANT DBA TO Mdian;


CREATE TABLE MDNDIALLO.CALL_HISTORY
(
  APPELANTS     VARCHAR2(200 BYTE),
  APPELES       VARCHAR2(200 BYTE),
  DATES         VARCHAR2(200 BYTE),
  HEURES        VARCHAR2(2 BYTE),
  DUREE         VARCHAR2(200 BYTE),
  IMSI          VARCHAR2(200 BYTE),
  IMEI          VARCHAR2(200 BYTE),
  LOCALISATION  VARCHAR2(50 BYTE),
  CELLULE_ID    VARCHAR2(200 BYTE),
  CELLULE_NAME  VARCHAR2(50 BYTE),
  VILLE         VARCHAR2(50 BYTE),
  PREFECTURE    VARCHAR2(50 BYTE),
  REGION        VARCHAR2(50 BYTE),
  TYPE          VARCHAR2(200 BYTE)
)


CREATE TABLE MDNDIALLO.UTILISATEUR
(
  NOM        VARCHAR2(255 BYTE),
  USERNAME   VARCHAR2(255 BYTE),
  PASSEWORD  VARCHAR2(255 BYTE),
  STATUT     VARCHAR2(20 BYTE),
  ETAT       NUMBER(1)                          DEFAULT 1
)

SELECT * FROM MDNDIALLO.CANDIDAT_VOTE_TRANSAC
where to_date(substr(CREATE_DATE, 1,10),'yyyy-MM-dd') between to_date(sysdate-10, 'yyyy-MM-dd') and to_date(sysdate-1, 'yyyy-MM-dd')  
order by CREATE_DATE desc