
insert into BIB_USER.UMD_BASE_STATION
select 
NEW_CGI BASE_STATION_ID,
CELLCODE BASE_STATION_CD,
case when substr(NEW_CGI,11,1) ='-' then substr(NEW_CGI,8,3) else substr(NEW_CGI,8,2) end BASE_STATION_LAC_CD, 
SITE_NAMES BASE_STATION_ADDRESS_TXT,
' ' BASE_STATION_BAND_TXT,
LATITUDE BASE_STATION_LAT_TXT,
LONGITUDE BASE_STATION_LONG_TXT,
' ' BASE_STATION_SITE_NM,
SITE_STATUS BASE_STATION_STATUS_TXT,
case when SITE_TYPE ='3G' then decode(SITE_TYPE,'3G','Y') else 'N' end BASE_STATION_3G_IND,
case when SITE_TYPE ='2G' then decode(SITE_TYPE,'2G','Y') else 'N' end BASE_STATION_2G_IND,
SITE_TYPE BASE_STATION_TECHNOLOGY_TXT,
' ' BASE_STATION_X_COORD_TXT,
' ' BASE_STATION_Y_COORD_TXT,
' 'BASE_STATION_SUBURB_LOC_TXT,
' ' BASE_STATION_SUBURB_SERV_TXT,
VILLE BASE_STATION_CITY_NM,
COMMUNES BASE_STATION_PROVINCE_NM,
'Guinee' BASE_STATION_COUNTRY_NM,
' ' BASE_STATION_GROUP_ID,
' ' BASE_STATION_GROUP_SITE_NM,
' ' FLEX_1,
' ' FLEX_2,
' ' FLEX_3,
' ' FLEX_4,
' ' FLEX_5,
' ' BASE_STATION_SUBURB_CD,
' ' BASE_STATION_CITY_CD,
'GN_NA' BASE_STATION_PROVINCE_GIS_CD,
PROVINCE_GOUVERNAURATS BASE_STATION_PROVINCE_CD,
REGION BASE_STATION_REGION_GIS_CD,
' ' BASE_STATION_REGION_CD,
' ' BASE_STATION_REGION_NM,
'GN' BASE_STATION_COUNTRY_GIS_CD,
'GN' BASE_STATION_COUNTRY_CD,
COMMUNES BASE_STATION_KPI_REGION_CD,
' ' BASE_STATION_KPI_SUB_REGION_CD
from IT_MK_CELLID_MAPPING@MKDBLINK a,IT_MK_CELLID_FINAL_2013@MKDBLINK
where CELLID= CELL_ID;

commit;

---------------
update IT_MK_CELLID_MAPPING
set NO=trim(NO),
COUNTRY=trim(COUNTRY),
PROVINCE_GOUVERNAURATS=trim(PROVINCE_GOUVERNAURATS),
REGION=trim(REGION),
SUB_REGION_COMMUNE_PREFECTURE=trim(SUB_REGION_COMMUNE_PREFECTURE),
TOWN=trim(TOWN),
SITE_CATAGORY=trim(SITE_CATAGORY),
TECHNOLOGY=trim(TECHNOLOGY),
SITE_PRIORITY=trim(SITE_PRIORITY),
C=trim(C),
SITE_NAME=trim(SITE_NAME),
CELL_ID=trim(CELL_ID),
CELL_NAME=trim(CELL_NAME),
LOCAL_CELL_ID_LTE=trim(LOCAL_CELL_ID_LTE),
CELL_FDD_TDD_INDICATION_LTE=trim(CELL_FDD_TDD_INDICATION_LTE),
BSC_NAME=trim(BSC_NAME),
BSC_ID=trim(BSC_ID),
RNC_NAME=trim(RNC_NAME),
RNC_ID=trim(RNC_ID),
EQUIPMENT_VENDOR=trim(EQUIPMENT_VENDOR),
INDOOR_OUTDOOR=trim(INDOOR_OUTDOOR),
LATITUDE=trim(LATITUDE),
LONGITUDE=trim(LONGITUDE);

commit;

----MCKINSEYDB
CREATE TABLE IT_MK_CELLID_MAPPING_BKP as
select *
from IT_MK_CELLID_MAPPING;

truncate table IT_MK_CELLID_MAPPING;

update IT_MK_CELLID_MAPPING
set BSC_NAME=''
WHERE BSC_NAME='NA';

update IT_MK_CELLID_MAPPING
set BSC_NAME=''
WHERE BSC_ID='NA';

update IT_MK_CELLID_MAPPING
set BSC_NAME=''
WHERE RNC_NAME='NA';

update IT_MK_CELLID_MAPPING
set BSC_NAME=''
WHERE RNC_ID='NA';

---- REPORTDB
CREATE TABLE BIB_USER.UMD_BASE_STATION_BKP AS
SELECT * FROM BIB_USER.UMD_BASE_STATION;

TRUNCATE TABLE BIB_USER.UMD_BASE_STATION;


insert into BIB_USER.UMD_BASE_STATION
select 
NEW_CGI BASE_STATION_ID,
CELLCODE BASE_STATION_CD,
case when substr(NEW_CGI,11,1) ='-' then substr(NEW_CGI,8,3) else substr(NEW_CGI,8,2) end BASE_STATION_LAC_CD, 
SITE_NAMES BASE_STATION_ADDRESS_TXT,
' ' BASE_STATION_BAND_TXT,
LATITUDE BASE_STATION_LAT_TXT,
LONGITUDE BASE_STATION_LONG_TXT,
' ' BASE_STATION_SITE_NM,
SITE_STATUS BASE_STATION_STATUS_TXT,
case when SITE_TYPE ='3G' then decode(SITE_TYPE,'3G','Y') else 'N' end BASE_STATION_3G_IND,
case when SITE_TYPE ='2G' then decode(SITE_TYPE,'2G','Y') else 'N' end BASE_STATION_2G_IND,
SITE_TYPE BASE_STATION_TECHNOLOGY_TXT,
' ' BASE_STATION_X_COORD_TXT,
' ' BASE_STATION_Y_COORD_TXT,
' 'BASE_STATION_SUBURB_LOC_TXT,
' ' BASE_STATION_SUBURB_SERV_TXT,
VILLE BASE_STATION_CITY_NM,
COMMUNES BASE_STATION_PROVINCE_NM,
'Guinee' BASE_STATION_COUNTRY_NM,
' ' BASE_STATION_GROUP_ID,
' ' BASE_STATION_GROUP_SITE_NM,
' ' FLEX_1,
' ' FLEX_2,
' ' FLEX_3,
' ' FLEX_4,
' ' FLEX_5,
' ' BASE_STATION_SUBURB_CD,
' ' BASE_STATION_CITY_CD,
'GN_NA' BASE_STATION_PROVINCE_GIS_CD,
PROVINCE_GOUVERNAURATS BASE_STATION_PROVINCE_CD,
REGION BASE_STATION_REGION_GIS_CD,
' ' BASE_STATION_REGION_CD,
' ' BASE_STATION_REGION_NM,
'GN' BASE_STATION_COUNTRY_GIS_CD,
'GN' BASE_STATION_COUNTRY_CD,
COMMUNES BASE_STATION_KPI_REGION_CD,
' ' BASE_STATION_KPI_SUB_REGION_CD
from IT_MK_CELLID_MAPPING@MKDBLINK a,IT_MK_CELLID_FINAL_2013@MKDBLINK
where CELLID= CELL_ID;

COMMIT;