-----CREATION DE LA TABLE DES TRANSACTIONS---
create table taf_taf_trans as
select 'D20180901' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180901_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'


insert into taf_taf_trans
select 'D20180902' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180902_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180903' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180903_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180904' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180904_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180905' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180905_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180906' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180906_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180907' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180907_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180908' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180908_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180909' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180909_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180910' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180910_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180911' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180911_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180912' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180912_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180913' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180913_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180914' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180914_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180915' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180915_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180916' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180916_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180917' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180917_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180918' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180918_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180919' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180919_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180920' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180920_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180921' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180921_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180922' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180922_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180923' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180923_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180924' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180924_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit; insert into taf_taf_trans
select 'D20180925' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180925_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; commit;



-----CREATION DE LA TABLE DE LOCALISATION---
create table localisation_pos as
select distinct(a.DEALER_MSISDN), b.REGION_NATURELLE, b.GOUVERNORATS, b.COMMUNES, b.VILLE
from REPORT_USER.IT_MK_TAF_TAF_DEALER_AREA_MJRH a, REPORT_USER.IT_MIS_CELLID_FINAL_2013 b 
where trim(a.CELL_ID)=trim(b.CELLID) and a.UTC_TIMESTAMP between '201806' and '201809'
and length(a.DEALER_MSISDN)=12

----REQUETE FINALE----------------
select * from
(
SELECT distinct(INITIATOR_MSISDN),
       sum(case when substr(TRANSACTION_DATE,1,7)= 'D201806' then AMOUNT end) JUNE_REV,
       sum(case when substr(TRANSACTION_DATE,1,7)= 'D201807' then AMOUNT end) JUL_REV,
       sum(case when substr(TRANSACTION_DATE,1,7)= 'D201808' then AMOUNT end) AUG_REV,
       sum(case when substr(TRANSACTION_DATE,1,7)= 'D201809' then AMOUNT end) SEP_REV
FROM taf_taf_trans
GROUP BY INITIATOR_MSISDN
) a,localisation_pos b
where a.INITIATOR_MSISDN=B.DEALER_MSISDN













-------CREATION DE LA TABLE DES TRANSACTIONS---
--create table taf_taf_trans as
--select 'D20180901' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180901_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--
--
--insert into taf_taf_trans
--select 'D20180902' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180902_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180903' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180903_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180904' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180904_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180905' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180905_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180906' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180906_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180907' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180907_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180908' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180908_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180909' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180909_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180910' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180910_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180911' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180911_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180912' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180912_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180913' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180913_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180914' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180914_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180915' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180915_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180916' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180916_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180917' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180917_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180918' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180918_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit; insert into taf_taf_trans
--select 'D20180919' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
--from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180919_TDR_DETAIL_CELLID_NW)
--where upper(RESULT_STATUS)='SUCCESS'
--and upper(SENDER_RESELLER_TYPE)='POS'
--and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
--and upper(REQUEST_AMOUNT_VALUE)<>'\N'
--; commit;

insert into taf_taf_trans
select 'D20180926' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180926_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; 
commit; 
insert into taf_taf_trans
select 'D20180927' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180927_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; 
commit; 
insert into taf_taf_trans
select 'D20180928' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180928_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; 
commit; 
insert into taf_taf_trans
select 'D20180929' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180929_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; 
commit; 
insert into taf_taf_trans
select 'D20180930' TRANSACTION_DATE,INITIATOR_MSISDN,REQUEST_AMOUNT_VALUE/100 AMOUNT
from REPORT_USER.IT_MIS_ERS_TDR_DETAIL_CELLIDNW partition(D20180930_TDR_DETAIL_CELLID_NW)
where upper(RESULT_STATUS)='SUCCESS'
and upper(SENDER_RESELLER_TYPE)='POS'
and upper(RECEIVER_AMOUNT_VALUE)<>'\N'
and upper(REQUEST_AMOUNT_VALUE)<>'\N'
; 
commit; 

select * from REPORT_USER.IT_MK_TAF_TAF_DEALER_AREA_MJRH group by UTC_TIMESTAMP

-----CREATION DE LA TABLE DE LOCALISATION---
create table localisation_pos as
select distinct(a.DEALER_MSISDN), b.REGION_NATURELLE, b.GOUVERNORATS, b.COMMUNES, b.VILLE
from tmp a, REPORT_USER.IT_MIS_CELLID_FINAL_2013 b 
where a.CELL_ID=b.CELLID(+)


----REQUETE FINALE----------------
select * from
(
SELECT distinct(INITIATOR_MSISDN),
       sum(case when substr(TRANSACTION_DATE,1,7)= 'D201806' then AMOUNT end) JUNE_REV,
       sum(case when substr(TRANSACTION_DATE,1,7)= 'D201807' then AMOUNT end) JUL_REV,
       sum(case when substr(TRANSACTION_DATE,1,7)= 'D201808' then AMOUNT end) AUG_REV,
       sum(case when substr(TRANSACTION_DATE,1,7)= 'D201809' then AMOUNT end) SEP_REV
FROM taf_taf_trans
GROUP BY INITIATOR_MSISDN
) a,localisation_pos b
where a.INITIATOR_MSISDN=B.DEALER_MSISDN(+)

select * from REPORT_USER.IT_MK_TAF_TAF_DEALER_AREA_MJRH

create table tmp as 
select DEALER_MSISDN,max(CELL_ID) CELL_ID 
from REPORT_USER.IT_MK_TAF_TAF_DEALER_AREA_MJRH 
where UTC_TIMESTAMP between '201803' and '201809'
group by DEALER_MSISDN
