----SAGE USER REVIEW
select *
from [dbo].[VW_USER_REVIEW_SAGE1000]

---- PHEB USER REVIEW 
select dbo.VW_LISTE_T_UTILISATEURS_PHEB.CODEUTILISATEUR,dbo.VW_LISTE_T_UTILISATEURS_PHEB.NOMUTILISATEUR,
dbo.VW_LISTE_T_UTILISATEURS_PHEB.PRENOMUTILISATEUR,
dbo.VW_LISTE_T_UTILISATEURS_PHEB.MAILUTILISATEUR,
dbo.VW_LISTE_T_UTILISATEURS_PHEB.PATRONYME,
dbo.VW_LISTE_T_UTILISATEURS_PHEB.CODEGROUPE,
dbo.VW_LISTE_T_UTILISATEURS_PHEB.EXPIRATIONLOGIN,dbo.VW_LAST_CONNEXION_USERS_PHEB.LAST_LOGIN_DATE
from dbo.VW_LISTE_T_UTILISATEURS_PHEB FULL OUTER JOIN  dbo.VW_LAST_CONNEXION_USERS_PHEB ON dbo.VW_LISTE_T_UTILISATEURS_PHEB.CODEUTILISATEUR=dbo.VW_LAST_CONNEXION_USERS_PHEB.CODEUTILISATEUR
--vue utilisateur pheb
select * from VW_LISTE_UTILISATEURS_PHEB_LAST

select *
from [dbo].[VW_USER_SAGE1000]
where Username in('mkcamara','iskaba','itraore','mnoulare','25-skouyate','08-amdiakite',
'10-mtcamara','abtoure','abdoulkarimsow','08-mycisse','10-ksmartin','26-madiallo','24-fkeita',
'30-mbconde','08-bthiam','11-fcamara','gabriel','tmassadan')

